# Generated by Django 2.0.7 on 2018-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
            ],
        ),
    ]
